name: EmpireBattles
version: 1.0.0
author: Tort
main: com.tort.EmpireBattles.Main
api-version: 1.14
depend:
  [PlayerParticles, dynmap]
permissions:
  Empires.server.bypass:
    description: Allows players to bypass the full server limit.
  Empires.server.balancebypass:
    description: Allows players to bypass the balancing system of teams.
  Empires.admin:
    description: Admin permission.
  empires.build:
    description: Build Permission
  empires.particles.flame:
    description: Permission to flame particle
  empires.particles.water:
    description: Permission to water particle
  empires.particles.chief:
    description: Permission to chief particle
  empires.particles.commander:
    description: Permission to commander particle
  empires.particles.general:
    description: Permission to general particle
  empires.particles.emperor:
    description: Permission to emperor particle
  empires.arrows.flame:
    description: Permission to flame trail
  empires.arrows.water:
      description: Permission to water trail
  empires.arrows.chief:
      description: Permission to chief trail
  empires.arrows.commander:
      description: Permission to commander trail
  empires.arrows.general:
      description: Permission to general trail
  empires.arrows.emperor:
      description: Permission to emperor trail

commands:
  empire:
    description: Used for empire commands
    usage: /<command>
    permission: Empires.empires
  reloadconfig:
    description: Used for reloading config
    usage: /<command>
    permission: Empires.reloadconfig
  empirejoin:
    description: Used for empire commands
    usage: /empire join <empire>
    permission: Empires.join
  empiretp:
    description: Tp to different worlds
    usage: /<command>
    permission: empires.empirestp

  help:
    description: Use /help
    usage: /<command>
    permission: empires.help

  setcapture:
    description: Set capture zone for empire.
    usage: /<command>
    permission: Empires.empires.setcapture

  spawn:
    description: Used to teleport to spawn.
    usage: /<command>
    permission: Empires.spawn
  town:
    description: town commands
    usage: /<command>
    permission: Empires.town

  capturetool:
    description: Get capture tool.
    usage: /<command>
    permission: Empires.capturetool

  start:
    description: Start game.
    usage: /<command>
    permission: Empires.start

  stopgame:
    description: Stop game.
    usage: /<command>
    permission: Empires.stop

  caplist:
    description: Get list of Capture zones
    usage: /<command>
    permission: Empires.caplist
  warp:
    description: Sends Player to town spawn
    usage: /<command>
    permission: Empires.warp
  empirelist:
    description: Shows number of towns each empire has
    usage: /<command>
    permission: Empires.empirelist
  team:
    description: Check team
    usage: /<command>
    permission: Empires.team

  smith:
    description: Open Smithing table
    usage: /<command>
    permission: Empires.smith
  stats:
    description: Show Player Stats
    usage: /<command>

  blockowner:
    description: Set the town for an ore
    usage: /<command>
    permission: Empires.blockowner

  setcolors:
    description: Set colors for empires
    usage: /<command>
    permission: Empires.setcolors

  resetgame:
    description: Reset game
    usage: /<command>
    permission: Empires.resetgame
  cannon:
    description: Get Cannon
    usage: /<command>
    permission: empires.cannon

  gate:
    description: Gate commands
    usage: /<command>
    permission: empires.gate

  empirechat:
    description: Enable and disable empire chat.
    usage: /<command>
    permission: Empires.empirechat
  particle:
    description: set particle
    usage: /<command>
    permission: empires.particles.particle

  resetStatus:
    description: Reset Empire Status
    usage: /<command>
    permission: empires.resetStatus

  resetTowns:
    description: Reset Town Ownership
    usage: /<command>
    permission: empires.resetTowns
  resetPlayers:
    description: Reset the empire of all players
    usage: /<command>
    permission: empires.resetPlayers
  toggleWhitelist:
    description: Turn Whitelist off
    usage: /<command>
    permission: empires.toggleWhitelist
  horse:
    description: Spawns player's horse
    usage: /<command>
  markerlist:
    description: Shows marker list
    usage: /<command>
  map:
    description: Sends link to map
    usage: /<command>
  list:
    description: List of players online
    usage: /<command>

  createnpc:
    description: Create NPC
    usage: /<command>
    permission: empires.createnpc

  npcs:
    description: Testing to see if the NPCs exist
    usage: /<command>
    permission: empires.npcs
  npcslayer:
    description: Gives npc slayer item
    usage: /<command>
    permission: empires.npcslayer
  pregame:
    description: Start pre-game
    usage: /<command>
    permission: empires.pregame